 - hosts: webserver
   vars_files:
    - ../Miscellaneous/vault.yml
   vars:
    ansible_become: yes
    ansible_become_pass: "{{ my_password }}"
   tasks:
   - name: Set a hostname
     hostname:
       name: webserver-vm
   - name: Update debian
     apt: 
       update_cache: true
   - name: Install JDK17
     apt:
       name: openjdk-17-jre
       state: latest
       update_cache: true
   - name: Install gnupg package
     apt:
       name: gnupg
       state: present
   - name: Add Opennebula-tools GPG key
     apt_key:
       url: https://downloads.opennebula.org/repo/repo.key
       state: present
   - name: Add Opennebula-tools repository
     apt_repository:
       repo: "deb https://downloads.opennebula.org/repo/5.6/Ubuntu/18.04 stable opennebula"
       state: present
    - name: Install Opennebula-tools browser
      apt:
        name: opennebula-tools
        state: present
   - name: Create directory www
     file:
       path: /www
       state: directory
   - name: Getting ServerFiles
     copy:
         src: ../Product/servers-shop-0.0.1-SNAPSHOT.jar
         dest: /www/servers-shop-0.0.1-SNAPSHOT.jar
   - name: Getting Application Properties
     copy:
         src: ../Product/application.properties
         dest: /www/application.properties
   - name: Getting Application Properties
     copy:
         src: ../Product/website.service
         dest: /etc/systemd/system/website.service
   - name: Start website Service
     systemd:
       name: website.service
