---
- hosts: client_vm
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install browser
      apt:
        name: firefox-esr
        update_cache: yes

    - name: Create Ordinary User
      user:
        name: ordinary_user
        password: "{{ 'user123' | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    - name: Add Ordinary User to sudo group
      user:
        name: ordinary_user
        groups: sudo
        append: yes

    - name: Install XFCE4
      apt:
        name: xfce4
        update_cache: yes